### ISSUE TITLE
Missing file: config.fs

### ISSUE THREAD

**Issue by ndalchau** [tpetricek/tomasp.net#2]
Hi Tomas, I wanted to see how you made your website (its really nice). However, the file expected at tools/config.fs is missing, so I can't build.
Neil

**Comment by tpetricek** [comment]
I have not particularly tried to make the site code reusable (would love that to happen though!) 

The `config.fs` file contains Azure connection string for the storage account where the site stores calendar photos, something like this:

```
module FsBlog.Config
let CalendarStorage = "DefaultEndpointsProtocol=(my secret key)"
```

I think if I was making this reusable, I'd just drop the "calendar" features because that's my special extension (which makes it harder to setup and nobody else probably needs it).
